### ISSUE TITLE
Support for  sensor_msgs/CompressedImage

### ISSUE THREAD

**Issue by unl0ck** [wesgood/RBSManager#9]
is it possible to support sensor_msgs/CompressedImage?
http://docs.ros.org/melodic/api/sensor_msgs/html/msg/CompressedImage.html

**Comment by wesgood** [comment]
I can add this message to the library but for now feel free to create a custom message for your specific project. There is a Python script in the repo that can help with it.

**Comment by unl0ck** [comment]
I Sent you an merge request. With the Message, was Created with your tool

Mit Freundlichen Grüßen

Simon Helming

**Comment by unl0ck** [comment]
I Wrote an merge request nur the Data Array is empty do you have an idea why?

Mit Freundlichen Grüßen

Simon Helming

**Comment by wesgood** [comment]
I haven't tested the CompressedImage message specifically (I'm mainly tied to the turtlesim) but I noticed the format of the nested message types is different than the messages in the pod already. Can you try configuring the values like TwistMessage? 

For that I'd suggest these changes:

- property titles are optional
- add init method with nested message types

**Comment by unl0ck** [comment]
okay I will test it and give you feedback

**Comment by unl0ck** [comment]
I wrote but now I got now nil instead of empty array...
```
import UIKit
import ObjectMapper
import RBSManager

public class CompressedImage: RBSMessage {
	public var header: Header?
	public var format: String?
    public var data: [UInt8]?
    
    public override init() {
        super.init()
        format = ""
        header = Header()
        data = [UInt8]()
    }
    public required init?(map: Map) {
        super.init(map: map)
    }
    

    public override func mapping(map: Map) {
	    header <- map["header"]
		format <- map["format"]
		data <- map["data"]
    }
}
```

**Comment by wesgood** [comment]
You should be able to use breakpoints inside the pod to see what is happening. Perhaps the incoming data doesn't match what is expected. If you can nail down where in the code it gets caught, I might be able to investigate further.

**Comment by unl0ck** [comment]
okay, but the change is like what do you want ? isn't it? 
I will investigate it. 
the rostopic echo show me the data correct.
alright. thanks for help

**Comment by unl0ck** [comment]
okay now I debugged it, and got follow result
the incoming message to RBSManager was

`"{\"topic\": \"/raspicam_node/image/compressed\", \"msg\": {\"header\": {\"stamp\": {\"secs\": 1548186301, \"nsecs\": 302186786}, \"frame_id\": \"raspicam\", \"seq\": 168}, \"data\": \"/9j/4QDeRXhpZgAATU0AKgAAAAgACAEAAAQAAAABAAAFAAEBAAQAAAABAAADwAEQAAIAAAAJAAAAbgEaAAUAAAABAAAAeAEbAAUAAAABAAAAgAEoAAMAAAABAAIAAAITAAMAAAABAAEAAIdpAAQAAAABAAAAiAAAAABCcm9hZGNvbQAAAAAASAAAAAEAAABIAAAAAQAGkAAABwAAAAQwMjIwkQEABwAAAAQBAgMAoAAABwAAAAQwMTAwoAEAAwAAAAEAAQAAoAIABAAAAAEAAAUAoAMABAAAAAEAAAPAAAAAAP/bAIQAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB/8AAEQgDwAUAAwEiAAIRAQMRAf/EAaIAAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKCxAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6AQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgsRAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQ"`


here you see the rostopic echo /raspicam_node/image/compressed output here it looks like an Array like the spec... so I am confused ... 
RBSManager tried to transformed into my CommpressedImage Class.
[compresedImage.txt](https://github.com/wesgood/RBSManager/files/2784447/compresedImage.txt)

```
header: 
  seq: 1202
  stamp: 
    secs: 1548188274
    nsecs: 559593839
  frame_id: "raspicam"
format: "jpg"
data: [255, 216, 255, 225, 0, 222, 69, 120, 105, 102, 0, 0, 77, 77, 0, 42, 0, 0, 0, 8, 0, 8, 1, 0, 0, 4, 0, 0, 0, 1, 0, 0, 5, 0, 1, 1, 0, 4, 0, 0, 0, 1, 0, 0, 3, 192, 1, 16, 0, 2, 0, 0, 0, 9, 0, 0, 0, 110, 1, 26, 0, 5, 0, 0, 0, 1, 0, 0, 0, 120, 1, 27, 0, 5, 0, 0, 0, 1, 0, 0, 0, 128, 1, 40, 0, 3, 0, 0, 0, 1, 0, 2, 0, 0, 2, 19, 0, 3, 0, 0, 0, 1, 0, 1, 0, 0, 135, 105, 0, 4, 0, 0, 0, 1, 0, 0, 0, 136, 0, 0, 0, 0, 66, 114, 111, 97, 100, 99, 111, 109, 0, 0, 0, 0, 0, 72, 0, 0, 0, 1, 0, 0, 0, 72, 0, 0, 0, 1, 0, 6, 144, 0, 0, 7, 0, 0, 0, 4, 48, 50, 50, 48, 145, 1, 0, 7, 0, 0, 0, 4, 1, 2, 3, 0, 160, 0, 0, 7, 0, 0, 0, 4, 48, 49, 48, 48, 160, 1, 0, 3, 0, 0, 0, 1, 0, 1, 0, 0, 160, 2, 0, 4, 0, 0, 0, 1, 0, 0, 5, 0, 160, 3, 0, 4, 0, 0, 0, 1, 0, 0, 3, 192, 0, 0, 0, 0, 255, 219, 0, 132, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...]
```
